---
- name: Setup Git PPA to use latest Git
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present
  when:
    - ansible_distribution == 'Ubuntu'
    - nvchad_ubuntu_git_latest | default(false) | bool
  tags: apt

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: apt

- name: Install APT packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt_packages }}"
  tags: apt

- name: Update installed git package
  ansible.builtin.apt:
    name: git
    state: latest
  tags: apt
