---
- name: Add custom PPA for Ubuntu
  ansible.builtin.apt_repository:
    repo: "ppa:neovim-ppa/unstable"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install neovim package
  ansible.builtin.apt:
    name: neovim
    state: present
