---
- name: Install NvChad with starter configuration
  become: true
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: https://github.com/NvChad/starter.git
    dest: ~/.config/nvim
    update: true
    force: true
  with_items: "{{ nvchad_users }}"
  tags: nvchad
