---
- name: Clone the NvChad repository
  become: true
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: https://github.com/NvChad/NvChad
    depth: 1
    dest: ~/.config/nvim
  with_items: "{{ nvchad_users }}"

- name: Install default configuration
  become: true
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: https://github.com/NvChad/example_config.git
    dest: ~/.config/nvim/lua/custom
  with_items: "{{ nvchad_users }}"
