---
- name: Install required Python packages
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items: "{{ python_packages }}"
  tags: python

- name: Install "coffee-script" node.js package globally.
  community.general.npm:
    name: tree-sitter-cli
    global: true
