---
- name: Remove ~/.config/nvim directory
  become: true
  become_user: "{{ item }}"
  ansible.builtin.file:
    path: "~/.config/nvim/"
    state: absent
  with_items: "{{ nvchad_users }}"
  tags:
    - uninstall

- name: Remove ~/.local/share/nvim directory
  become: true
  become_user: "{{ item }}"
  ansible.builtin.file:
    path: "~/.local/share/nvim/"
    state: absent
  with_items: "{{ nvchad_users }}"
  tags:
    - uninstall

- name: Remove ~/.cache/nvim directory
  become: true
  become_user: "{{ item }}"
  ansible.builtin.file:
    path: "~/.cache/nvim/"
    state: absent
  with_items: "{{ nvchad_users }}"
  tags:
    - uninstall
