---
- name: Converge
  hosts: all
  become: true
  become_user: root

  vars:
    nodejs_version: "20.x"
    nodejs_install_npm_user: root
    nvchad_users: root

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_os_family == 'Debian'

  roles:
    - role: tolecnal.nvchad
