---
- name: Converge
  hosts: all
  become: true
  become_user: root

  vars:
    nodejs_version: "20.x"
    nodejs_install_npm_user: root
    nvchad_users: root

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Check if EXTERNALLY-MANAGED file exists
      ansible.builtin.stat:
        path: /usr/lib/python3.11/EXTERNALLY-MANAGED
      register: file_stat

    - name: Remove EXTERNALLY-MANAGED file if it exists
      ansible.builtin.file:
        path: /usr/lib/python3.11/EXTERNALLY-MANAGED
        state: absent
      when: file_stat.stat.exists
      changed_when: false

  roles:
    - role: tolecnal.nvchad
